In [3]:
!pip install qiskit
!pip install qiskit --quiet
!pip install qiskit-aer --quiet
!pip install pylatexenc --quiet
!pip install qiskit-machine-learning --quiet

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.9/231.9 kB 9.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.8/6.8 MB 71.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 37.3/37.3 MB 20.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.6/49.6 MB 11.2 MB/s eta 0:00:00


In [10]:
# Install necessary packages (if not installed)
!pip install qiskit qiskit-machine-learning matplotlib --quiet

# Imports
from qiskit_machine_learning.neural_networks import SamplerQNN
from qiskit.circuit.library import TwoLocal
from qiskit.primitives import StatevectorSampler
from qiskit.visualization import plot_histogram
import numpy as np
import matplotlib.pyplot as plt

# Ensure inline plotting (for Jupyter/Colab)
%matplotlib inline

# Step 1: Define a parameterized feature map (2 qubits)
feature_map = TwoLocal(
    num_qubits=2,
    rotation_blocks='ry',
    entanglement_blocks='cz',
    reps=1
)

# Step 2: Define the SamplerQNN
sampler = StatevectorSampler()
qnn = SamplerQNN(
    circuit=feature_map,
    sampler=sampler,
    input_params=feature_map.parameters,  # Input features
    weight_params=[],                     # No trainable weights for now
)

# Step 3: Provide sample input values
num_inputs = len(feature_map.parameters)
x_input = np.random.rand(num_inputs) * 2 * np.pi  # Random values in [0, 2π]

# Step 4: Evaluate the QNN output
output = qnn.forward(x_input, weights=np.array([]))
print("Input values for QNN (radians):")
print(x_input)
print("\nQuantum Neural Network output (probabilities):")
print(output)

# Step 5: Convert probabilities to counts for histogram
probs = np.real(output[0])
probs /= np.sum(probs)  # ensure normalization

shots = 1024  # number of simulated measurements
counts = (probs * shots).astype(int)  # convert probabilities to counts

states = [format(i, f"0{feature_map.num_qubits}b") for i in range(len(counts))]
counts_dict = dict(zip(states, counts))

# Step 6: Plot histogram
fig = plot_histogram(counts_dict)
fig.suptitle("QNN Output Probabilities for Input Vector")
plt.show(fig)


Input values for QNN (radians):
[3.91240939 1.64121513 2.87348018 6.07730044]

Quantum Neural Network output (probabilities):
[[0.35351562 0.04589844 0.49316406 0.10742188]]


In [11]:
# Install necessary packages
!pip install qiskit qiskit-machine-learning matplotlib --quiet

# Imports
from qiskit_machine_learning.neural_networks import SamplerQNN
from qiskit.circuit.library import TwoLocal
from qiskit.primitives import StatevectorSampler
from qiskit.visualization import plot_histogram
import numpy as np
import matplotlib.pyplot as plt

# Ensure inline plotting (for Jupyter/Colab)
%matplotlib inline

# Step 1: Define a parameterized feature map (2 qubits)
feature_map = TwoLocal(
    num_qubits=2,
    rotation_blocks='ry',
    entanglement_blocks='cz',
    reps=1
)

# Step 2: Define the SamplerQNN
sampler = StatevectorSampler()
qnn = SamplerQNN(
    circuit=feature_map,
    sampler=sampler,
    input_params=feature_map.parameters,  # Input features
    weight_params=[],                     # No trainable weights for now
)

# Step 3: Provide sample input values
num_inputs = len(feature_map.parameters)
x_input = np.random.rand(num_inputs) * 2 * np.pi  # Random values in [0, 2π]

# Step 4: Evaluate the QNN output
output = qnn.forward(x_input, weights=np.array([]))
print("Input values for QNN (radians):")
print(x_input)

# Step 5: Extract probabilities
probs = np.real(output[0])
probs /= np.sum(probs)  # Ensure normalization
print("\nQuantum Neural Network output (probabilities):")
for i, p in enumerate(probs):
    state = format(i, f"0{feature_map.num_qubits}b")
    print(f"|{state}⟩ → {p:.4f}")

# Step 6: Convert probabilities to counts for histogram
shots = 1024
counts = (probs * shots).astype(int)
states = [format(i, f"0{feature_map.num_qubits}b") for i in range(len(counts))]
counts_dict = dict(zip(states, counts))

# Step 7: Plot histogram
fig = plot_histogram(counts_dict)
fig.suptitle("QNN Output Probabilities for Input Vector")
plt.show(fig)


Input values for QNN (radians):
[5.1297009  1.44756876 0.37248017 2.55359669]

Quantum Neural Network output (probabilities):
|00⟩ → 0.0771
|01⟩ → 0.2744
|10⟩ → 0.6289
|11⟩ → 0.0195
